/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  safelist: [
    'opacity-0',
    'opacity-100',
    'group-hover:opacity-100',
    'hover:text-blue-600',
    'hover:text-gray-500',
    'text-gray-300',
  ],
  theme: {
    extend: {
      zIndex: {
        '100': '100',
      },
      fontFamily: {
        sans: ['Sora', 'system-ui', '-apple-system', 'sans-serif'],
        heading: ['Sora', 'system-ui', 'sans-serif'],
        headline: ['Crimson Pro', 'serif'],
        data: ['JetBrains Mono', 'monospace'],
        body: ['Inter', 'sans-serif'],
      },
      colors: {
        primary: 'var(--color-primary)',
        ink: 'var(--color-ink)',
        slate: 'var(--color-slate)',
        'brand-teal': 'var(--color-brand-teal)',
        'brand-yellow': 'var(--color-brand-yellow)',
        'brand-coral': 'var(--color-brand-coral)',
        'brand-blue': 'var(--color-brand-blue)',
        'teal-light': 'var(--color-teal-light)',
        'coral-light': 'var(--color-coral-light)',
        hairline: 'var(--color-hairline)',
        'hairline-soft': 'var(--color-hairline-soft)',
        surface: 'var(--color-surface)',
        canvas: 'var(--color-canvas)',
        'surface-soft': 'var(--color-surface-soft)',
        'on-surface-variant': 'var(--color-on-surface-variant)',
        'on-primary': 'var(--color-on-primary)',
        success: 'var(--color-success)',
        error: 'var(--color-error)',
        warning: 'var(--color-warning)',
        accent: 'var(--color-accent)',
        /* Machine Ledger colors */
        'ml-surface': '#fff9ef',
        'ml-surface-dim': '#dfd9d0',
        'ml-surface-bright': '#fff9ef',
        'ml-surface-container-lowest': '#ffffff',
        'ml-surface-container-low': '#f9f3e9',
        'ml-surface-container': '#f3ede3',
        'ml-surface-container-high': '#ede7de',
        'ml-surface-container-highest': '#e7e2d8',
        'ml-on-surface': '#1d1b16',
        'ml-on-surface-variant': '#434749',
        'ml-inverse-surface': '#32302a',
        'ml-inverse-on-surface': '#f6f0e6',
        'ml-outline': '#747879',
        'ml-outline-variant': '#c3c7c8',
        'ml-surface-tint': '#586062',
        'ml-primary': '#181f21',
        'ml-on-primary': '#ffffff',
        'ml-primary-container': '#2d3436',
        'ml-on-primary-container': '#959c9f',
        'ml-inverse-primary': '#c1c8ca',
        'ml-secondary': '#675c54',
        'ml-on-secondary': '#ffffff',
        'ml-secondary-container': '#efe0d5',
        'ml-on-secondary-container': '#6d625a',
        'ml-tertiary': '#152023',
        'ml-on-tertiary': '#ffffff',
        'ml-tertiary-container': '#2a3538',
        'ml-on-tertiary-container': '#929da2',
        'ml-error': '#ba1a1a',
        'ml-on-error': '#ffffff',
        'ml-error-container': '#ffdad6',
        'ml-on-error-container': '#93000a',
        'ml-primary-fixed': '#dde4e6',
        'ml-primary-fixed-dim': '#c1c8ca',
        'ml-on-primary-fixed': '#161d1f',
        'ml-on-primary-fixed-variant': '#41484a',
        'ml-secondary-fixed': '#efe0d5',
        'ml-secondary-fixed-dim': '#d2c4b9',
        'ml-on-secondary-fixed': '#211a14',
        'ml-on-secondary-fixed-variant': '#4e453d',
        'ml-tertiary-fixed': '#d9e4e9',
        'ml-tertiary-fixed-dim': '#bdc8cd',
        'ml-on-tertiary-fixed': '#131d21',
        'ml-on-tertiary-fixed-variant': '#3e484c',
        'ml-background': '#fff9ef',
        'ml-on-background': '#1d1b16',
        'ml-surface-variant': '#e7e2d8',
        'ml-ink-black': '#2D3436',
        'ml-ink-grey': '#636E72',
        'ml-ledger-paper': '#FDFBF7',
        'ml-parchment-base': '#FCF8F3',
        'ml-surface-highlight': '#E8DFD0',
        'ml-faded-border': '#B2A59B',
      },
      borderRadius: {
        'ml-sm': '0.25rem',
        'ml': '0.5rem',
        'ml-md': '0.75rem',
        'ml-lg': '1rem',
        'ml-xl': '1.5rem',
      },
    },
  },
  plugins: [],
}
